pub const AurPackage = struct {
    Id: u32,
    Name: [:0]const u8,
    PackageBaseId: u32,
    PackageBase: [:0]const u8,
    Version: [:0]const u8,
    Description: ?[:0]const u8 = null,
    Url: ?[:0]const u8 = null,
    NumVotes: u32,
    Popularity: f64,
    OutOfDate: ?i64 = null,
    Maintainer: ?[:0]const u8 = null,
    FirstSubmitted: i64,
    LastModified: i64,
    UrlPath: [:0]const u8,
    Depends: ?[]const [:0]const u8 = null,
    MakeDepends: ?[]const [:0]const u8 = null,
    OptDepends: ?[]const [:0]const u8 = null,
    CheckDepends: ?[]const [:0]const u8 = null,
    Conflicts: ?[]const [:0]const u8 = null,
    Provides: ?[]const [:0]const u8 = null,
    Replaces: ?[]const [:0]const u8 = null,
    Groups: ?[]const [:0]const u8 = null,
    License: ?[]const [:0]const u8 = null,
    Keywords: ?[]const [:0]const u8 = null,
    Explicit: bool = false,
};
