# Fish shell completions for shelly
# Auto-generated from the Shelly CLI command structure. Do not edit by hand.

# Disable file completions by default
complete -c shelly -f

# --- global options ---
complete -c shelly -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -l verbose -s v -d "Enable verbose logging."

complete -c shelly -n "__fish_use_subcommand" -a query -d "Query repositories and packages"
complete -c shelly -n "__fish_use_subcommand" -a install -d "Install packages"
complete -c shelly -n "__fish_use_subcommand" -a upgrade -d "Perform a full system upgrade"
complete -c shelly -n "__fish_use_subcommand" -a upgrade-all -d "Upgrade all packages from every source (repo, AUR, Flatpak, AppImage)"
complete -c shelly -n "__fish_use_subcommand" -a downgrade -d "Downgrade a package"
complete -c shelly -n "__fish_use_subcommand" -a ignore -d "Manage ignored packages"
complete -c shelly -n "__fish_use_subcommand" -a news -d "Show ArchLinux news"
complete -c shelly -n "__fish_use_subcommand" -a cache-clean -d "Clean the local cache"
complete -c shelly -n "__fish_use_subcommand" -a check-updates -d "Check for package updates"
complete -c shelly -n "__fish_use_subcommand" -a list-updates -d "List standard packages that have available updates"
complete -c shelly -n "__fish_use_subcommand" -a export -d "Export the current system state to a file"
complete -c shelly -n "__fish_use_subcommand" -a fix-permissions -d "Fix permissions for Shelly directories"
complete -c shelly -n "__fish_use_subcommand" -a mark -d "Mark a package as explicit or a dependency"
complete -c shelly -n "__fish_use_subcommand" -a purify -d "Remove corrupted/orphaned packages"
complete -c shelly -n "__fish_use_subcommand" -a remove -d "Remove packages (repo or local binary)"
complete -c shelly -n "__fish_use_subcommand" -a sync -d "Syncs the system with the current state"
complete -c shelly -n "__fish_use_subcommand" -a update -d "Update specific packages"
complete -c shelly -n "__fish_use_subcommand" -a docs -d "Generate Markdown reference documentation for the Shelly CLI"
complete -c shelly -n "__fish_use_subcommand" -a appimage -d "Manage AppImages"
complete -c shelly -n "__fish_use_subcommand" -a config -d "Manage shelly configuration"
complete -c shelly -n "__fish_use_subcommand" -a aur -d "Manage AUR packages"
complete -c shelly -n "__fish_use_subcommand" -a keyring -d "Manage the pacman keyring"
complete -c shelly -n "__fish_use_subcommand" -a flatpak -d "Manage flatpak"
complete -c shelly -n "__fish_seen_subcommand_from query" -l repos -s r -d "List available repositories. This supercedes any other modifiers."
complete -c shelly -n "__fish_seen_subcommand_from query" -l available -s a -d "Include available packages in the search"
complete -c shelly -n "__fish_seen_subcommand_from query" -l installed -s i -d "Include installed packages in the search"
complete -c shelly -n "__fish_seen_subcommand_from query" -l local -s l -d "Include local packages in the search"
complete -c shelly -n "__fish_seen_subcommand_from query" -l take -s t -d "Number of results to return" -r
complete -c shelly -n "__fish_seen_subcommand_from query" -l page -s p -d "Page number" -r
complete -c shelly -n "__fish_seen_subcommand_from query" -l show-hidden -s w -d "Show hidden packages"
complete -c shelly -n "__fish_seen_subcommand_from query" -l detail -l info -s d -d "Show detailed information for a single package"
complete -c shelly -n "__fish_seen_subcommand_from query" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from query" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from query" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from query" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from install" -l build-deps -s b -d "Install build dependencies"
complete -c shelly -n "__fish_seen_subcommand_from install" -l make-deps -s m -d "Install make dependencies"
complete -c shelly -n "__fish_seen_subcommand_from install" -l no-deps -s d -d "Install without checking/installing dependencies"
complete -c shelly -n "__fish_seen_subcommand_from install" -l upgrade -s u -d "Upgrades the packages if they are already installed"
complete -c shelly -n "__fish_seen_subcommand_from install" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from install" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from install" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from install" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from upgrade" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from upgrade" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from upgrade" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from upgrade" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l no-repo -d "Skip the standard repository (ALPM) upgrade"
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l no-aur -d "Skip the AUR upgrade"
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l no-flatpak -d "Skip the Flatpak upgrade"
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l no-appimage -d "Skip the AppImage upgrade"
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from upgrade-all" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l oldest -s o -d "Installs the oldest matched version (default newest)"
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l ignore -s i -d "Add to IgnorePkg list"
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l list-options -s l -d "List available downgrade versions"
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l target -s t -d "Install a specific downgrade target by exact version or package filename" -r
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from downgrade" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l list -s l -d "List ignored packages"
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l add -s a -d "Add a package to the ignore list"
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l remove -s r -d "Remove a package from the ignore list"
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l clear -s c -d "Clear the ignore list"
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from ignore" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from news" -l all -s a -d "Show all news, not just news you haven't seen before."
complete -c shelly -n "__fish_seen_subcommand_from news" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from news" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from news" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from news" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l keep -s k -d "Keep the specified number of versions in the cache. Defaults to 3." -r
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l uninstalled -s i -d "Remove only uninstalled packages from the cache."
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l dry-run -s d -d "Show what would be removed."
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l cache-dir -s c -d "Path to the cache directory." -r
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l target -s t -d "Remove only the specified packages from the cache." -r
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from cache-clean" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from check-updates" -l aur -s a -d "Check for AUR updates"
complete -c shelly -n "__fish_seen_subcommand_from check-updates" -l flatpak -s l -d "Check for Flatpak updates"
complete -c shelly -n "__fish_seen_subcommand_from check-updates" -l count -s c -d "Returns the number of updates"
complete -c shelly -n "__fish_seen_subcommand_from check-updates" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from check-updates" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from check-updates" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from check-updates" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from list-updates" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from list-updates" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from list-updates" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from list-updates" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from export" -l name -s a -d "The name of the exported file" -r
complete -c shelly -n "__fish_seen_subcommand_from export" -l output -s o -d "The default output location for the sync file" -r
complete -c shelly -n "__fish_seen_subcommand_from export" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from export" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from export" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from export" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from fix-permissions" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from fix-permissions" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from fix-permissions" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from fix-permissions" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from mark" -l explicit -s e -d "Mark the package as explicit"
complete -c shelly -n "__fish_seen_subcommand_from mark" -l depends -s d -d "Mark the package as a dependency"
complete -c shelly -n "__fish_seen_subcommand_from mark" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from mark" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from mark" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from mark" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from purify" -l dry-run -s d -d "Show what would be removed without removing it."
complete -c shelly -n "__fish_seen_subcommand_from purify" -l orphans -s o -d "Also remove orphaned dependencies."
complete -c shelly -n "__fish_seen_subcommand_from purify" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from purify" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from purify" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from purify" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from remove" -l cascade -s c -d "Removes all things the removed package(s) are dependent on that have no other uses"
complete -c shelly -n "__fish_seen_subcommand_from remove" -l opt-deps -s o -d "Removes optional dependencies installed with the package, that don't depend on other packages"
complete -c shelly -n "__fish_seen_subcommand_from remove" -l ripple -s i -d "Removes packages that depend on the package being removed"
complete -c shelly -n "__fish_seen_subcommand_from remove" -l remove-config -s r -d "Removes any files in your ~/.config that can be tied exclusively to the removed package(s). EXPERIMENTAL"
complete -c shelly -n "__fish_seen_subcommand_from remove" -l local -s l -d "Force removal as a locally-installed binary package"
complete -c shelly -n "__fish_seen_subcommand_from remove" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from remove" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from remove" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from remove" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from sync" -l force -s f -d "Force a sync"
complete -c shelly -n "__fish_seen_subcommand_from sync" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from sync" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from sync" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from sync" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from update" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from update" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from update" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from update" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from docs" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from docs" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from docs" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from docs" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a install -d "Install an AppImage"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a remove -d "Remove an AppImage"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a list -d "Lists all AppImages"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a upgrade -d "Upgrades all AppImages"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a sync-meta -d "Syncs meta data for an AppImage"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a list-updates -d "Find Updates for an AppImage"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a configure-updates -d "Configures the update settings for an AppImage"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and not __fish_seen_subcommand_from install remove list upgrade sync-meta list-updates configure-updates migrate-manager" -a migrate-manager -d "Updates the AppImage manager version"
complete -c shelly -n "__fish_seen_subcommand_from appimage" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from install" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from install" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from install" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from install" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from remove" -l remove-config -s c -d "Remove Config"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from remove" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from remove" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from remove" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from remove" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from upgrade" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from upgrade" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from upgrade" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from upgrade" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from sync-meta" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from sync-meta" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from sync-meta" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from sync-meta" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list-updates" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list-updates" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list-updates" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from list-updates" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from configure-updates" -l prerelease -s p -d "Allow prerelease updates"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from configure-updates" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from configure-updates" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from configure-updates" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from configure-updates" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from migrate-manager" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from migrate-manager" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from migrate-manager" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from appimage; and __fish_seen_subcommand_from migrate-manager" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from get set list reset parallel" -a get -d "Get a configuration value"
complete -c shelly -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from get set list reset parallel" -a set -d "Set a configuration value"
complete -c shelly -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from get set list reset parallel" -a list -d "List all configuration values"
complete -c shelly -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from get set list reset parallel" -a reset -d "Reset the configuration to defaults"
complete -c shelly -n "__fish_seen_subcommand_from config; and not __fish_seen_subcommand_from get set list reset parallel" -a parallel -d "Set the number of parallel downloads"
complete -c shelly -n "__fish_seen_subcommand_from config" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from config" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from config" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from config" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from get" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from set" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from list" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from list" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from list" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from list" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from reset" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from reset" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from reset" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from reset" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from parallel" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from parallel" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from parallel" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from config; and __fish_seen_subcommand_from parallel" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a install -d "Install AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a install-version -d "Install a specific version of an AUR package"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a remove -d "Remove AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a update -d "Rebuild and reinstall specific AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a upgrade -d "Upgrade all out-of-date AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a list -d "List installed AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a list-updates -d "List AUR packages that have available updates"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a search -d "Search the Arch User Repository"
complete -c shelly -n "__fish_seen_subcommand_from aur; and not __fish_seen_subcommand_from install install-version remove update upgrade list list-updates search search-pkgbuild" -a search-pkgbuild -d "Fetch and display the PKGBUILD of AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l build-deps -s o -d "Install build dependencies only for the specified AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l make-deps -s m -d "Install make dependencies only for the specified AUR packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l chroot -s c -d "Build packages in a clean chroot environment using makechrootpkg"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l check -d "Run the check() function during AUR package builds (disabled by default)"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install-version" -l check -d "Run the check() function during AUR package builds (disabled by default)"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install-version" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install-version" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install-version" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from install-version" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from remove" -l cascade -s c -d "Removes all things the removed package(s) are dependent on that have no other uses"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from remove" -l opt-deps -s o -d "Removes optional dependencies installed with the package, that don't depend on other packages"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from remove" -l ripple -s i -d "Removes packages that depend on the package being removed"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from remove" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from remove" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from remove" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from remove" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from update" -l check -d "Run the check() function during AUR package builds (disabled by default)"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from update" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from update" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from update" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from update" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from upgrade" -l check -d "Run the check() function during AUR package builds (disabled by default)"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from upgrade" -l singlepane -d "Render output as a single pacman-style linear stream"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from upgrade" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from upgrade" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from upgrade" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from upgrade" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list" -l show-hidden -d "Include hidden packages in the listing"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list-updates" -l show-hidden -d "Include hidden packages in the listing"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list-updates" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list-updates" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list-updates" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from list-updates" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search-pkgbuild" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search-pkgbuild" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search-pkgbuild" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from aur; and __fish_seen_subcommand_from search-pkgbuild" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from keyring" -l keyserver -d "The keyserver to use" -r
complete -c shelly -n "__fish_seen_subcommand_from keyring" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from keyring" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from keyring" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from keyring" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a install -d "Install flatpak app"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a update -d "Update flatpak app"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a list -d "List installed flatpak apps"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a list-updates -d "List flatpak apps with updates"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a running -d "List running flatpak apps"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a repair -d "Repairs Flatpak Installation"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a uninstall -d "Remove flatpak app"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a run -d "Run flatpak app"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a kill -d "Kill running flatpak app"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a search -d "Search flatpak"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a sync-remote-appstream -d "Sync remote appstream"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a get-remote-appstream -d "Returns remote appstream json"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a upgrade -d "Upgrade all flatpak apps"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a list-remotes -d "Returns all remotes currently added"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a add-remotes -d "Adds a flatpak remote"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a remove-remotes -d "Removes a flatpak remote"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a install-ref-file -d "Installs flatpak app from ref file"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a install-bundle -d "Installs flatpak app from bundle file"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and not __fish_seen_subcommand_from install update list list-updates running repair uninstall run kill search sync-remote-appstream get-remote-appstream upgrade list-remotes add-remotes remove-remotes install-ref-file install-bundle app-remote-info" -a app-remote-info -d "Get app remote info"
complete -c shelly -n "__fish_seen_subcommand_from flatpak" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l user -d "Install to user scope instead of system scope"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l remote -s r -d "Remote to install from (e.g., flathub, flathub-beta)" -r
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l branch -s b -d "Branch to install (e.g., stable, beta). Defaults to stable" -r
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l runtime -d "Install as a runtime instead of an application"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from update" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from update" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from update" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from update" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-updates" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-updates" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-updates" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-updates" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from running" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from running" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from running" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from running" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from repair" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from repair" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from repair" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from repair" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from uninstall" -l remove-unused -s r -d "Remove unused dependencies after uninstalling"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from uninstall" -l config -s c -d "Removes flatpak configuration for removed app"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from uninstall" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from uninstall" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from uninstall" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from uninstall" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from run" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from run" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from run" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from run" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from kill" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from kill" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from kill" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from kill" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from search" -l limit -s l -d "Maximum number of search results to display per page" -r
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from search" -l page -s p -d "Page number for paginated results (starts at 1)" -r
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from search" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from search" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from search" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from search" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from sync-remote-appstream" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from sync-remote-appstream" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from sync-remote-appstream" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from sync-remote-appstream" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from get-remote-appstream" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from get-remote-appstream" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from get-remote-appstream" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from get-remote-appstream" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from upgrade" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from upgrade" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from upgrade" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from upgrade" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-remotes" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-remotes" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-remotes" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from list-remotes" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from add-remotes" -l remote-url -s u -d "Flatpak remote URL" -r
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from add-remotes" -l system -s s -d "Add the remote system-wide"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from add-remotes" -l gpg-verify -s g -d "Enable GPG verification for the remote"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from add-remotes" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from add-remotes" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from add-remotes" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from add-remotes" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from remove-remotes" -l system -s s -d "Remove the remote system-wide"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from remove-remotes" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from remove-remotes" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from remove-remotes" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from remove-remotes" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-ref-file" -l system -s s -d "Install system-wide"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-ref-file" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-ref-file" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-ref-file" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-ref-file" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-bundle" -l system -s s -d "Install system-wide"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-bundle" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-bundle" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-bundle" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from install-bundle" -l verbose -s v -d "Enable verbose logging."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from app-remote-info" -l no-confirm -s n -d "Disable confirmation prompts"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from app-remote-info" -l ui-mode -s U -d "Enable UI mode"
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from app-remote-info" -l json -s j -d "Output results in JSON format for scripting."
complete -c shelly -n "__fish_seen_subcommand_from flatpak; and __fish_seen_subcommand_from app-remote-info" -l verbose -s v -d "Enable verbose logging."
