const std = @import("std");
const spec = @import("spec.zig");

pub fn render(
    allocator: std.mem.Allocator,
    manifest: *const spec.Manifest,
    writer: *std.Io.Writer,
) !void {
    try writer.writeAll(
        \\# Shelly CLI Documentation
        \\
        \\> Auto-generated by `shelly utility --docs` (`shelly -Td`).
        \\
        \\## Overview
        \\
    );
    try writeText(writer, manifest.root().description orelse "");
    try writer.writeAll("\n\n## Commands\n\n| Command | Description |\n| --- | --- |\n");
    for (manifest.commands) |*command| {
        if (!isChildOf(command, manifest.root())) continue;
        try writer.print("| `{s}` | ", .{command.path});
        try writeCell(writer, command.description orelse "");
        try writer.writeAll(" |\n");
    }

    try writer.writeAll("\n## Shortcodes\n\n| Shortcode | Command |\n| --- | --- |\n");
    for (manifest.commands) |*command| {
        if (!command.hasAction) continue;
        const action_code = command.actionCode orelse continue;
        try writer.print("| `-{c}", .{action_code});
        if (command.typeCode) |type_code| try writer.print("{c}", .{type_code});
        try writer.print("` | `{s}` |\n", .{displayPath(command)});
    }

    try writer.writeAll("\n## Global Options\n\n");
    try writeOptions(writer, manifest.root().options);

    try writer.writeAll("\n## Command Reference\n");
    for (manifest.commands) |*action| {
        if (!isChildOf(action, manifest.root())) continue;
        try writeAction(allocator, manifest, action, writer);
    }
}

fn writeAction(
    allocator: std.mem.Allocator,
    manifest: *const spec.Manifest,
    action: *const spec.Command,
    writer: *std.Io.Writer,
) !void {
    try writer.print("\n### `{s}`\n\n", .{action.path});
    try writeText(writer, action.description orelse "");
    try writer.writeAll("\n");

    const default_child = manifest.findDefaultChild(action);
    var other_children: std.ArrayList(*const spec.Command) = .empty;
    for (manifest.commands) |*child| {
        if (!isChildOf(child, action) or child == default_child) continue;
        try other_children.append(allocator, child);
    }

    if (other_children.items.len > 0) {
        try writer.writeAll("\nSubcommands:\n\n| Command | Description |\n| --- | --- |\n");
        for (other_children.items) |child| {
            try writer.print("| `{s}` | ", .{child.path});
            try writeCell(writer, child.description orelse "");
            try writer.writeAll(" |\n");
        }
    }

    if (default_child) |child| try writeCommandDetails(child, action.path, writer);
    for (other_children.items) |child| {
        try writer.print("\n#### `{s}`\n\n", .{child.path});
        try writeText(writer, child.description orelse "");
        try writer.writeAll("\n");
        try writeCommandDetails(child, child.path, writer);
    }
}

fn writeCommandDetails(
    command: *const spec.Command,
    path: []const u8,
    writer: *std.Io.Writer,
) !void {
    try writer.writeAll("\nUsage:\n\n```text\n");
    try writer.print("{s}", .{path});
    for (command.arguments) |argument| {
        try writer.writeByte(' ');
        if (argument.minimumArity == 0) try writer.writeByte('[');
        try writer.print("<{s}>", .{argument.name});
        if (argument.maximumArity == null or (argument.maximumArity orelse 1) > 1)
            try writer.writeAll("...");
        if (argument.minimumArity == 0) try writer.writeByte(']');
    }
    if (command.options.len > 0) try writer.writeAll(" [options]");
    try writer.writeAll("\n```\n");

    if (command.arguments.len > 0) {
        try writer.writeAll("\nArguments:\n\n| Argument | Arity | Description |\n| --- | --- | --- |\n");
        for (command.arguments) |argument| {
            try writer.print("| `<{s}>` | ", .{argument.name});
            if (argument.maximumArity) |maximum|
                try writer.print("{d}..{d}", .{ argument.minimumArity, maximum })
            else
                try writer.print("{d}..*", .{argument.minimumArity});
            try writer.writeAll(" | ");
            try writeCell(writer, argument.description orelse "");
            try writer.writeAll(" |\n");
        }
    }

    if (command.options.len > 0) {
        try writer.writeAll("\nOptions:\n\n");
        try writeOptions(writer, command.options);
    }
}

fn writeOptions(writer: *std.Io.Writer, options: []const spec.Option) !void {
    try writer.writeAll("| Option | Type | Description |\n| --- | --- | --- |\n");
    for (options) |option| {
        if (option.hidden or option.builtIn) continue;
        try writer.writeAll("| `");
        try writer.writeAll(option.name);
        for (option.aliases) |alias| try writer.print(", {s}", .{alias});
        if (!std.mem.eql(u8, option.type, "bool") and !std.mem.eql(u8, option.type, "void"))
            try writer.print(" <{s}>", .{std.mem.trimStart(u8, option.name, "-")});
        try writer.print("` | `{s}` | ", .{option.type});
        try writeCell(writer, option.description orelse "");
        if (option.choices.len > 0) {
            try writer.writeAll(" Choices: ");
            for (option.choices, 0..) |choice, index| {
                if (index > 0) try writer.writeAll(", ");
                try writer.print("`{s}`", .{choice});
            }
            try writer.writeByte('.');
        }
        try writer.writeAll(" |\n");
    }
}

fn displayPath(command: *const spec.Command) []const u8 {
    if (command.defaultForAction) return command.parentPath orelse command.path;
    return command.path;
}

fn isChildOf(command: *const spec.Command, parent: *const spec.Command) bool {
    const parent_path = command.parentPath orelse return false;
    return std.mem.eql(u8, parent_path, parent.path);
}

fn writeText(writer: *std.Io.Writer, value: []const u8) !void {
    for (value) |byte| try writer.writeByte(if (byte == '\r') ' ' else byte);
}

fn writeCell(writer: *std.Io.Writer, value: []const u8) !void {
    for (value) |byte| switch (byte) {
        '|' => try writer.writeAll("\\|"),
        '\r', '\n' => try writer.writeByte(' '),
        else => try writer.writeByte(byte),
    };
}

test "renders catalog-driven Markdown with utility and shell choices" {
    var arena = std.heap.ArenaAllocator.init(std.testing.allocator);
    defer arena.deinit();
    const manifest = try spec.Manifest.load(arena.allocator());
    var output = std.Io.Writer.Allocating.init(std.testing.allocator);
    defer output.deinit();

    try render(arena.allocator(), &manifest, &output.writer);
    const markdown = output.writer.buffered();
    try std.testing.expect(std.mem.startsWith(u8, markdown, "# Shelly CLI Documentation\n"));
    try std.testing.expect(std.mem.indexOf(u8, markdown, "`shelly utility --docs`") != null);
    try std.testing.expect(std.mem.indexOf(u8, markdown, "| `-T` | `shelly utility` |") != null);
    try std.testing.expect(std.mem.indexOf(u8, markdown, "`--completions, -c <completions>`") != null);
    try std.testing.expect(std.mem.indexOf(u8, markdown, "`--pacfiles, -p`") != null);
    try std.testing.expect(std.mem.indexOf(u8, markdown, "`--threeway, -3`") != null);
    try std.testing.expect(std.mem.indexOf(u8, markdown, "`bash`, `fish`, `zsh`") != null);
    try std.testing.expect(std.mem.indexOf(u8, markdown, "shelly utility utility") == null);
    try std.testing.expect(std.mem.indexOf(u8, markdown, "shelly docs") == null);
}

test "escapes Markdown table cells" {
    var output = std.Io.Writer.Allocating.init(std.testing.allocator);
    defer output.deinit();
    try writeCell(&output.writer, "one|two\nthree");
    try std.testing.expectEqualStrings("one\\|two three", output.writer.buffered());
}
