//! Public API for Shelly's GTK user interface.

/// GLib 2 bindings generated by zig-gobject.
pub const glib = @import("glib2");

/// GObject 2 bindings generated by zig-gobject.
pub const gobject = @import("gobject2");

/// GIO 2 bindings generated by zig-gobject.
pub const gio = @import("gio2");

/// Pango 1 bindings generated by zig-gobject.
pub const pango = @import("pango1");

/// GTK 4 bindings generated by zig-gobject.
pub const gtk = @import("gtk4");

/// GDK 4 bindings generated by zig-gobject.
pub const gdk = @import("gdk4");

pub const std = @import("std");

test "GTK 4 binding is available from the package root" {
    try std.testing.expectEqual(
        @as(c_uint, gtk.MAJOR_VERSION),
        gtk.getMajorVersion(),
    );
}
