const std = @import("std");

pub const Info = struct {
    package_base: ?[]u8 = null,
    package_names: [][]u8,

    pub fn deinit(self: *Info, allocator: std.mem.Allocator) void {
        if (self.package_base) |package_base| allocator.free(package_base);
        for (self.package_names) |name| allocator.free(name);
        allocator.free(self.package_names);
        self.* = undefined;
    }

    pub fn contains(self: *const Info, package_name: []const u8) bool {
        if (self.package_base) |package_base|
            if (std.mem.eql(u8, package_base, package_name)) return true;
        for (self.package_names) |name|
            if (std.mem.eql(u8, name, package_name)) return true;
        return false;
    }
};

pub fn parse(allocator: std.mem.Allocator, content: []const u8) !Info {
    var package_base: ?[]u8 = null;
    errdefer if (package_base) |value| allocator.free(value);
    var names: std.ArrayList([]u8) = .empty;
    errdefer {
        for (names.items) |name| allocator.free(name);
        names.deinit(allocator);
    }

    var lines = std.mem.splitScalar(u8, content, '\n');
    while (lines.next()) |raw| {
        const line = std.mem.trim(u8, raw, " \t\r");
        if (line.len == 0 or line[0] == '#') continue;
        const equal = std.mem.indexOfScalar(u8, line, '=') orelse continue;
        const key = std.mem.trim(u8, line[0..equal], " \t");
        const value = std.mem.trim(u8, line[equal + 1 ..], " \t");
        if (value.len == 0) continue;

        if (std.mem.eql(u8, key, "pkgbase")) {
            if (package_base) |old| allocator.free(old);
            package_base = try allocator.dupe(u8, value);
        } else if (std.mem.eql(u8, key, "pkgname")) {
            var duplicate = false;
            for (names.items) |name| {
                if (std.mem.eql(u8, name, value)) {
                    duplicate = true;
                    break;
                }
            }
            if (!duplicate) try names.append(allocator, try allocator.dupe(u8, value));
        }
    }

    return .{
        .package_base = package_base,
        .package_names = try names.toOwnedSlice(allocator),
    };
}

pub fn parseFile(allocator: std.mem.Allocator, io: std.Io, path: []const u8) !Info {
    const content = try std.Io.Dir.cwd().readFileAlloc(io, path, allocator, .unlimited);
    defer allocator.free(content);
    return parse(allocator, content);
}

test ".SRCINFO parser resolves split package members" {
    var info = try parse(std.testing.allocator,
        \\# generated by makepkg
        \\pkgbase = demo-suite
        \\pkgname = demo-cli
        \\pkgname = demo-ui
        \\pkgname = demo-ui
    );
    defer info.deinit(std.testing.allocator);
    try std.testing.expectEqualStrings("demo-suite", info.package_base.?);
    try std.testing.expect(info.contains("demo-ui"));
    try std.testing.expect(info.contains("demo-suite"));
    try std.testing.expect(!info.contains("missing"));
    try std.testing.expectEqual(@as(usize, 2), info.package_names.len);
}
